### ISSUE TITLE
docker container fails to start with FRB_ROUTING_NUMBER and FRB_DOWNLOAD_CODE set in env

### ISSUE THREAD

**Issue by anujtewari** [moov-io/fed#186]
Docker container fails to start when FRB_ROUTING_NUMBER and FRB_DOWNLOAD_CODE is set

Steps to reproduce
- start the docker container with env variables
    - FRB_ROUTING_NUMBER=121212
    - FRB_DOWNLOAD_CODE=121212
- the container fails to start with error - panic: problem downloading fedach: temp file: open /tmp/fedach-3993745650: no such file or directory

Full stack trace
```
ts=2022-08-02T19:29:10Z msg="Starting fed server version v0.8.1" level=info
ts=2022-08-02T19:29:10Z msg="download: attempting fedach" level=info
ts=2022-08-02T19:29:10Z msg="listening on [::]:9096" level=info
ts=2022-08-02T19:29:11Z msg="admin: problem starting admin http: http: Server closed" level=info
panic: problem downloading fedach: temp file: open /tmp/fedach-3993745650: no such file or directory

goroutine 1 [running]:
main.fedACHDataFile({0xa11860?, 0xc00000c1c8?})
        /go/src/github.com/moov-io/fed/cmd/server/reader.go:20 +0x174
main.main()
        /go/src/github.com/moov-io/fed/cmd/server/main.go:114 +0x506
ts=2022-08-02T19:29:16Z msg="Starting fed server version v0.8.1" level=info
ts=2022-08-02T19:29:16Z msg="download: attempting fedach" level=info
ts=2022-08-02T19:29:16Z msg="listening on [::]:9096" level=info
ts=2022-08-02T19:29:17Z msg="admin: problem starting admin http: http: Server closed" level=info
panic: problem downloading fedach: temp file: open /tmp/fedach-183196970: no such file or directory

goroutine 1 [running]:
main.fedACHDataFile({0xa11860?, 0xc0000a01c8?})
        /go/src/github.com/moov-io/fed/cmd/server/reader.go:20 +0x174
main.main()
        /go/src/github.com/moov-io/fed/cmd/server/main.go:114 +0x506

```
Looks the error is coming from download.go:90 -> `ioutil.TempFile(downloadDirectory, fmt.Sprintf("%s-*", listName))`
Digging more, error happens when in os/tempfile.go -> `OpenFile(name, O_RDWR|O_CREATE|O_EXCL, 0600)`

**Comment by adamdecaf** [comment]
It looks like we can keep these in memory rather than downloading to a file. It'll work around the permissions issue.

https://github.com/moov-io/fed/pull/187
